In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [3]:
#Read in dataset
df = pd.read_csv('CleanedInterviews - 04.14.18.csv')

In [ ]:
df.head(10)

In [36]:
#Using label encoder to label variables
label = LabelEncoder()

#example for converting a list
sample_list = ['a','b','b','a','c','a','d']
new_list = label.fit_transform(sample_list)
print(new_list)

[0 1 1 0 2 0 3]

In [24]:
#trying out selecting subset of data using list of column names
#creating own dataset as pandas dataframe

mydata = {'Name':['john','dave','sly','shy','shay'], 
          'Age': [21, 22, 23, 24, 25], 
          'Weight': [123, 125, 127, 129, 131]}


expDF = pd.DataFrame(mydata)
print(expDF)

   Age  Name  Weight
0   21  john     123
1   22  dave     125
2   23   sly     127
3   24   shy     129
4   25  shay     131

In [34]:
expDF[['Name','Age']]

   Name  Age
0  john   21
1  dave   22
2   sly   23
3   shy   24
4  shay   25

In [37]:
#selecting the subset of our dataset to be features in DT. 
cols = df.columns
print(cols)
print(type(cols))

#Choosing specific columns. Starting with the easy ones first
chosenColumns = ['Client name', 'Industry', 'Location', 'position',
        'Interview Type', 'Gender', 'necessary_permission',
       'unscheduled_meetings', 'followup_3hours_call', 'alternative_number',
       'resume_printout_JD', 'venue_details', 'shared_call_letter',
       'Expected Attendance', 'Marital Status']

Index(['Date of Interview', 'Client name', 'Industry', 'Location', 'position',
       'skillset', 'Interview Type', 'Gender', 'Candidate Current Location',
       'Candidate Job Location', 'Interview Venue',
       'Candidate Native location', 'necessary_permission',
       'unscheduled_meetings', 'followup_3hours_call', 'alternative_number',
       'resume_printout_JD', 'venue_details', 'shared_call_letter',
       'Expected Attendance', 'Observed Attendance', 'Marital Status'],
      dtype='object')
<class 'pandas.core.indexes.base.Index'>

In [40]:
#need to convert to list, because we can converst list to integers
#cols = chosenColumns.tolist()
#initializing new empty Pandas DataFrame
df_1 = pd.DataFrame()

#Interating over our list to append columns to new DataFrame
for column in chosenFeatures:
    #print(column)
    #doing a transformation for each column in cols to convert from type 'object' to 'string'
    df_1[column] = label.fit_transform(df[column].astype('str'))
    
print(df_1.head(5))

   Client name  Industry  Location  position  Interview Type  Gender  \
0            7         5         2         0               1       1
1            7         5         2         0               1       1
2            7         5         2         0               1       1
3            7         5         2         0               1       1
4            7         5         2         0               1       1

   necessary_permission  unscheduled_meetings  followup_3hours_call  \
0                     1                     1                     1
1                     1                     1                     1
2                     2                     0                     2
3                     1                     1                     0
4                     1                     1                     1

   alternative_number  resume_printout_JD  venue_details  shared_call_letter  \
0                   1                   1              1                   1
1                   1                   1              1                   1
2                   2                   2              2                   2
3                   1                   0              1                   1
4                   0                   1              1                   1

   Expected Attendance  Marital Status
0                    1               1
1                    1               1
2                    0               1
3                    0               1
4                    0               0

In [1]:
#then you can write the new dataset to file
#df_1.to_csv('CleanedInterviews - NumericVariables', encoding='utf-8', index=False)

interviews = pd.read_csv('D:\Spring 18\ML\Project\CleanedInterviews - 04.14.18.csv')

NameError: name 'pd' is not defined

In [3]:
interviews = pd.read_csv('D:\Spring 18\ML\Project\CleanedInterviews - 04.14.18.csv')

In [4]:
interviews.head()

,Date of Interview,Client name,Industry,Location,position,skillset,Interview Type,Gender,Candidate Current Location,Candidate Job Location,...,necessary_permission,unscheduled_meetings,followup_3hours_call,alternative_number,resume_printout_JD,venue_details,shared_call_letter,Expected Attendance,Observed Attendance,Marital Status
0,13.02.2015,Hospira,Pharmaceuticals,Chennai,Niche,Routine,Scheduled Walk-In,Male,Chennai,Hosur,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
1,13.02.2015,Hospira,Pharmaceuticals,Chennai,Niche,Routine,Scheduled Walk-In,Male,Chennai,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
2,13.02.2015,Hospira,Pharmaceuticals,Chennai,Niche,Routine,Scheduled Walk-In,Male,Chennai,Chennai,...,NaN,No,NaN,NaN,NaN,NaN,NaN,No,No,Single
3,13.02.2015,Hospira,Pharmaceuticals,Chennai,Niche,Routine,Scheduled Walk-In,Male,Chennai,Chennai,...,Yes,Yes,No,Yes,No,Yes,Yes,No,No,Single
4,13.02.2015,Hospira,Pharmaceuticals,Chennai,Niche,Routine,Scheduled Walk-In,Male,Chennai,Bangalore,...,Yes,Yes,Yes,No,Yes,Yes,Yes,No,No,Married

In [5]:
interviews=interviews.apply(LabelEncoder().fit_transform)

TypeError: ("'<' not supported between instances of 'float' and 'str'", 'occurred at index Date of Interview')

In [6]:
interviews.drop['Date of Interview']

TypeError: 'method' object is not subscriptable

In [8]:
del interviews['Date of Interview']
interviews

In [16]:
for columns in interviews:
interviews = interviews.apply(LabelEncoder().fit_transform(interviews[columns].astype('str')))

IndentationError: expected an indented block (<ipython-input-16-b6a2b626f414>, line 2)

In [17]:
interviews1 = pd.read_csv('D:\Spring 18\ML\Project\CleanedInterviews - 04.14.18.csv')

In [18]:
interviews1.head()

,Date of Interview,Client name,Industry,Location,position,skillset,Interview Type,Gender,Candidate Current Location,Candidate Job Location,...,necessary_permission,unscheduled_meetings,followup_3hours_call,alternative_number,resume_printout_JD,venue_details,shared_call_letter,Expected Attendance,Observed Attendance,Marital Status
0,13.02.2015,Hospira,Pharmaceuticals,Chennai,Niche,Routine,Scheduled Walk-In,Male,Chennai,Hosur,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
1,13.02.2015,Hospira,Pharmaceuticals,Chennai,Niche,Routine,Scheduled Walk-In,Male,Chennai,Bangalore,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Single
2,13.02.2015,Hospira,Pharmaceuticals,Chennai,Niche,Routine,Scheduled Walk-In,Male,Chennai,Chennai,...,NaN,No,NaN,NaN,NaN,NaN,NaN,No,No,Single
3,13.02.2015,Hospira,Pharmaceuticals,Chennai,Niche,Routine,Scheduled Walk-In,Male,Chennai,Chennai,...,Yes,Yes,No,Yes,No,Yes,Yes,No,No,Single
4,13.02.2015,Hospira,Pharmaceuticals,Chennai,Niche,Routine,Scheduled Walk-In,Male,Chennai,Bangalore,...,Yes,Yes,Yes,No,Yes,Yes,Yes,No,No,Married

In [19]:
interviews1=interviews1.apply(LabelEncoder().fit_transform)

TypeError: ("'<' not supported between instances of 'float' and 'str'", 'occurred at index Date of Interview')

In [20]:
interviews1=interviews1.dropna()

In [21]:
interviews1=interviews1.apply(LabelEncoder().fit_transform)

In [22]:
intervies1.head()

NameError: name 'intervies1' is not defined

In [36]:
interviews1

,Date of Interview,Client name,Industry,Location,position,skillset,Interview Type,Gender,Candidate Current Location,Candidate Job Location,...,Candidate Native location,necessary_permission,unscheduled_meetings,followup_3hours_call,alternative_number,resume_printout_JD,venue_details,shared_call_letter,Expected Attendance,Marital Status
0,17,7,5,2,0,63,1,1,2,4,...,17,1,1,1,1,1,1,1,1,1
1,17,7,5,2,0,63,1,1,2,1,...,33,1,1,1,1,1,1,1,1,1
3,17,7,5,2,0,63,1,1,2,2,...,8,1,1,0,1,0,1,1,0,1
4,17,7,5,2,0,63,1,1,2,1,...,8,1,1,1,0,1,1,1,0,0
5,17,1,4,4,0,63,1,1,4,3,...,15,1,1,1,1,1,1,1,1,1
6,17,1,4,4,0,63,1,1,4,3,...,15,1,1,1,1,1,1,1,1,1
7,17,1,4,4,0,63,1,0,4,3,...,26,1,1,1,1,1,1,1,1,1
8,17,1,4,4,0,63,1,1,4,3,...,14,1,1,1,1,1,1,1,1,1
9,17,1,4,4,0,63,1,0,4,3,...,14,1,1,1,1,1,1,1,1,1
10,31,12,4,1,0,63,1,1,1,1,...,10,1,1,1,1,1,1,1,1,1
11,31,12,4,1,0,63,1,0,1,1,...,34,0,1,0,0,1,1,1,0,1
12,31,12,4,1,0,63,1,1,1,1,...,6,1,1,1,1,1,1,1,1,1
13,31,12,4,1,0,63,1,1,1,1,...,34,0,1,1,1,1,1,0,0,1
14,31,12,4,1,0,63,1,1,1,1,...,10,1,1,1,1,1,1,1,1,1
15,31,12,4,1,0,63,1,0,1,1,...,10,1,1,1,1,1,1,1,1,1
16,31,12,4,1,0,63,1,0,1,1,...,34,1,1,1,1,1,1,1,1,1
17,31,12,4,1,0,63,1,0,1,1,...,6,0,1,1,0,1,1,1,0,1
18,31,12,4,1,0,63,1,1,1,1,...,10,1,1,1,1,1,1,1,1,1
19,31,12,4,1,0,63,1,1,1,1,...,10,1,1,1,1,1,1,1,1,1
20,31,12,4,1,0,63,1,1,1,1,...,34,0,1,1,1,1,1,0,0,1
21,31,12,4,1,0,63,1,1,1,1,...,34,1,1,1,1,1,1,1,1,1
22,31,12,4,1,0,63,1,1,1,1,...,10,1,1,1,1,1,1,1,1,1
23,31,12,4,1,0,63,1,1,1,1,...,10,1,1,1,1,1,1,1,1,1
24,31,12,4,1,0,63,1,1,1,1,...,34,1,1,1,0,0,1,1,0,1
25,31,12,4,1,0,63,1,1,1,1,...,10,0,0,1,1,1,1,0,0,1
26,31,12,4,1,0,63,1,1,1,1,...,6,0,1,1,1,1,1,0,0,0
27,31,12,4,1,0,63,1,1,1,1,...,6,0,1,1,1,0,1,0,0,1
28,44,10,0,2,0,63,1,0,2,2,...,8,1,1,1,1,1,1,1,1,0
29,44,10,0,2,0,63,1,0,2,2,...,8,1,1,1,1,1,1,1,1,0
30,44,10,0,2,0,63,1,0,2,2,...,8,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202,71,10,0,2,1,29,1,1,2,2,...,8,1,1,1,1,1,1,1,1,0
1203,71,10,0,2,1,29,1,1,2,2,...,8,1,1,1,1,1,1,1,1,1
1204,73,10,0,2,1,30,1,1,2,2,...,8,1,1,1,1,1,1,1,1,1
1205,69,10,0,2,1,30,1,0,2,2,...,12,1,1,1,1,1,1,1,1,1
1206,69,10,0,2,1,30,1,1,2,2,...,18,1,1,1,1,1,1,1,1,0
1207,69,10,0,2,1,30,1,1,2,2,...,8,1,1,1,1,1,1,1,1,0
1208,69,10,0,2,1,30,1,1,2,2,...,8,1,1,1,1,1,1,1,1,0
1209,69,10,0,2,1,30,1,1,2,2,...,8,1,1,1,1,1,1,1,1,1
1210,69,10,0,2,1,30,1,1,2,2,...,11,1,1,1,1,1,1,1,1,0
1211,68,10,0,2,1,29,1,1,2,2,...,8,1,1,1,1,1,1,1,1,1
1212,68,10,0,2,1,29,1,1,2,2,...,8,1,1,1,1,1,1,1,1,1
1213,68,10,0,2,1,29,1,1,2,2,...,8,1,1,1,1,1,1,1,1,0
1214,67,10,0,2,1,29,1,0,2,2,...,8,1,1,1,1,1,1,1,1,0
1215,69,10,0,2,1,29,1,1,2,2,...,8,1,1,1,1,1,1,1,1,1
1216,69,10,0,2,1,29,1,1,2,2,...,8,1,1,1,1,1,1,1,1,1
1217,5,8,5,2,0,13,0,1,2,2,...,8,1,1,1,1,1,1,1,1,0
1218,5,8,5,2,0,61,0,1,2,2,...,8,1,1,1,1,1,1,1,1,0
1219,5,8,5,2,0,61,0,1,2,2,...,8,1,1,1,1,1,1,1,1,0
1220,5,8,5,2,0,61,0,1,2,2,...,8,1,1,1,1,1,1,1,1,1
1221,5,8,5,2,0,20,0,1,2,2,...,8,1,1,1,1,1,1,1,1,1
1222,5,8,5,2,0,20,0,1,2,2,...,18,1,1,1,1,1,1,1,1,0
1223,5,8,5,2,0,20,0,1,2,2,...,18,1,1,1,1,1,1,1,1,0
1224,5,8,5,2,0,13,0,1,2,2,...,39,1,1,1,1,1,1,1,1,0
1225,5,8,5,2,0,48,0,1,2,2,...,39,1,1,1,1,1,1,1,1,1
1226,5,8,5,2,0,53,0,1,2,2,...,8,1,1,1,1,1,1,1,1,0
1227,5,8,5,2,0,53,0,1,2,2,...,8,1,1,1,1,1,1,1,1,0
1228,5,8,5,2,0,80,0,1,2,2,...,6,1,1,1,1,1,1,1,1,0
1229,5,8,5,2,0,13,0,1,2,2,...,18,1,1,1,1,1,1,1,1,1
1230,4,8,5,2,0,13,0,1,2,2,...,18,1,1,1,1,1,1,1,1,0
1231,4,8,5,2,0,80,0,1,2,2,...,8,1,1,1,1,1,1,1,1,1

In [25]:
interviews1['Date of Interview'].value_counts()

3     198
77     86
53     43
18     41
0      34
36     32
2      30
33     24
54     24
5      23
31     18
40     18
69     16
21     15
84     15
49     14
71     14
20     13
37     12
6      12
51     12
57     11
55     11
75     11
30     11
52     11
43     11
65     11
79     10
66     10
     ...
48      3
38      2
46      2
32      2
27      2
9       2
56      2
47      2
62      2
81      2
4       2
29      2
63      2
76      1
64      1
82      1
67      1
73      1
15      1
12      1
13      1
14      1
16      1
61      1
35      1
39      1
59      1
58      1
72      1
60      1
Name: Date of Interview, Length: 85, dtype: int64

In [26]:
from sklearn.linear_model import LogisticRegression
Y_train=interviews1['Observed Attendance']
del interviews1['Observed Attendance']
X_train = interviews1
interviews1.head()

,Date of Interview,Client name,Industry,Location,position,skillset,Interview Type,Gender,Candidate Current Location,Candidate Job Location,...,Candidate Native location,necessary_permission,unscheduled_meetings,followup_3hours_call,alternative_number,resume_printout_JD,venue_details,shared_call_letter,Expected Attendance,Marital Status
0,17,7,5,2,0,63,1,1,2,4,...,17,1,1,1,1,1,1,1,1,1
1,17,7,5,2,0,63,1,1,2,1,...,33,1,1,1,1,1,1,1,1,1
3,17,7,5,2,0,63,1,1,2,2,...,8,1,1,0,1,0,1,1,0,1
4,17,7,5,2,0,63,1,1,2,1,...,8,1,1,1,0,1,1,1,0,0
5,17,1,4,4,0,63,1,1,4,3,...,15,1,1,1,1,1,1,1,1,1

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train, Y_train, test_size=0.33, random_state=42)
log=LogisticRegression()
log.fit(X_train,y_train)
score = log.score(X_test, y_test)
print(score)

ValueError: Found input variables with inconsistent numbers of samples: [659, 984]

In [34]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
randomf = RandomForestClassifier(n_jobs=2, random_state=0)
randomf.fit(X_train,y_train)
y_pred = randomf.predict(Y_train)
print(accuracy_score(y_test, y_pred))

ValueError: Expected 2D array, got 1D array instead:
array=[ 0.  0.  0.  0.  1.  1.  1.  1.  0.  1.  0.  1.  1.  1.  1.  1.  0.  1.
  0.  0.  1.  1.  1.  0.  0.  0.  0.  1.  1.  1.  0.  1.  0.  0.  1.  1.
  0.  1.  1.  0.  1.  0.  1.  0.  1.  1.  1.  1.  1.  1.  0.  1.  0.  1.
  1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  0.  0.  1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  1.
  1.  0.  0.  1.  0.  0.  1.  1.  1.  0.  1.  1.  0.  1.  1.  1.  1.  0.
  0.  1.  1.  0.  1.  1.  1.  1.  0.  1.  1.  0.  0.  1.  0.  1.  0.  0.
  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  0.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  1.  1.  1.  1.
  0.  1.  1.  1.  0.  0.  1.  1.  1.  1.  0.  1.  1.  0.  0.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.
  1.  0.  1.  0.  1.  0.  0.  0.  1.  1.  0.  0.  0.  0.  1.  1.  0.  1.
  1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.  1.  0.  1.  0.  0.  1.  1.
  1.  1.  0.  1.  1.  1.  1.  0.  1.  1.  1.  0.  1.  0.  1.  1.  1.  0.
  0.  0.  1.  1.  1.  0.  1.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  0.  0.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.
  1.  1.  0.  1.  1.  1.  1.  1.  0.  1.  0.  1.  1.  0.  1.  1.  1.  1.
  1.  1.  0.  1.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  1.  0.
  0.  1.  1.  0.  1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  0.  1.  1.  0.
  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  0.  0.  1.
  1.  0.  0.  1.  1.  1.  0.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  0.
  1.  1.  1.  0.  1.  1.  0.  0.  1.  1.  1.  1.  1.  0.  0.  1.  1.  0.
  0.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.
  1.  1.  0.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  1.  1.  0.  1.
  1.  1.  1.  0.  1.  1.  1.  1.  1.  0.  1.  0.  1.  1.  1.  0.  1.  1.
  1.  0.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  0.  0.  1.  1.  1.  1.
  1.  1.  0.  1.  0.  1.  1.  1.  1.  1.  1.  1.  0.  0.  1.  0.  1.  1.
  1.  1.  0.  0.  1.  1.  1.  1.  1.  0.  1.  1.  1.  0.  0.  0.  1.  1.
  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.
  1.  1.  1.  0.  0.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  0.  0.  1.  0.  1.  0.  1.  1.
  1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  0.  0.  1.  1.  0.  1.  1.  1.  1.  0.  1.  1.  1.  1.  0.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  1.  0.  1.  1.  1.  1.  0.  0.
  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.
  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  1.  1.  1.  1.  0.
  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  0.  0.  0.  1.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  1.  1.
  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  0.  0.  1.  0.  1.  1.  1.  1.  0.  0.  1.  1.  1.  1.  1.  0.  1.
  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.
  1.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  0.  0.  1.  1.
  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.  0.  1.  1.  1.  0.  1.  1.  1.
  1.  0.  1.  0.  0.  1.  1.  1.  0.  1.  0.  0.  0.  1.  0.  1.  1.  0.
  0.  0.  1.  1.  1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  1.  1.  1.  1.
  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.  1.
  1.  0.  1.  1.  1.  1.  0.  1.  1.  0.  1.  1.  1.  0.  0.  1.  0.  0.
  0.  1.  1.  1.  1.  1.  0.  1.  0.  0.  1.  1.  1.  1.  0.  1.  1.  0.
  0.  1.  1.  1.  1.  0.  1.  1.  1.  1.  0.  0.  1.  1.  0.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [35]:
interviews1.corr()

,Date of Interview,Client name,Industry,Location,position,skillset,Interview Type,Gender,Candidate Current Location,Candidate Job Location,...,Candidate Native location,necessary_permission,unscheduled_meetings,followup_3hours_call,alternative_number,resume_printout_JD,venue_details,shared_call_letter,Expected Attendance,Marital Status
Date of Interview,1.000000,0.019658,-0.141748,-0.109011,-0.051441,0.163891,0.166324,-0.056216,-0.109011,-0.064740,...,-0.137005,-0.050842,0.005164,0.035401,-0.000003,-0.023218,-0.001915,-0.030328,-0.036741,0.091714
Client name,0.019658,1.000000,-0.394944,-0.456229,0.429164,0.032695,0.354579,0.010881,-0.456229,-0.376647,...,-0.114752,-0.016763,0.022042,0.054909,0.032102,0.010160,0.019023,0.027718,0.017899,-0.006316
Industry,-0.141748,-0.394944,1.000000,0.335287,-0.423474,0.232109,-0.308447,0.034547,0.335287,0.341251,...,0.153663,-0.245566,-0.248618,-0.221951,-0.188826,-0.199138,-0.165873,-0.200461,-0.248239,-0.160895
Location,-0.109011,-0.456229,0.335287,1.000000,-0.082975,0.123850,-0.340940,-0.045981,1.000000,0.816061,...,0.200540,0.030127,0.030781,-0.053203,-0.030076,-0.025195,-0.013943,-0.024713,-0.054433,-0.022316
position,-0.051441,0.429164,-0.423474,-0.082975,1.000000,-0.317918,0.380049,-0.017120,-0.082975,0.012619,...,-0.143367,0.180155,0.112453,0.043548,0.093617,0.097453,0.091951,0.096457,0.186404,0.068641
skillset,0.163891,0.032695,0.232109,0.123850,-0.317918,1.000000,-0.303681,-0.055464,0.123850,0.100979,...,0.025922,-0.194189,-0.089955,-0.042934,-0.117416,-0.078144,-0.087038,-0.130858,-0.202855,-0.068943
Interview Type,0.166324,0.354579,-0.308447,-0.340940,0.380049,-0.303681,1.000000,-0.005554,-0.340940,-0.324151,...,-0.191094,0.097609,0.026018,-0.006326,0.020967,0.034290,0.003117,0.051881,0.116276,0.050913
Gender,-0.056216,0.010881,0.034547,-0.045981,-0.017120,-0.055464,-0.005554,1.000000,-0.045981,-0.027133,...,0.038561,0.052591,0.017270,0.009650,0.100680,0.046514,0.027956,0.079231,0.043894,0.216333
Candidate Current Location,-0.109011,-0.456229,0.335287,1.000000,-0.082975,0.123850,-0.340940,-0.045981,1.000000,0.816061,...,0.200540,0.030127,0.030781,-0.053203,-0.030076,-0.025195,-0.013943,-0.024713,-0.054433,-0.022316
Candidate Job Location,-0.064740,-0.376647,0.341251,0.816061,0.012619,0.100979,-0.324151,-0.027133,0.816061,1.000000,...,0.225791,0.037491,-0.002150,-0.060378,-0.008733,-0.031704,0.002197,-0.043975,-0.051408,-0.051906
Interview Venue,-0.116572,-0.423593,0.372307,0.908234,-0.083770,0.127985,-0.341541,-0.020762,0.908234,0.889204,...,0.242409,0.043822,0.010927,-0.070428,-0.027491,-0.022011,-0.009721,-0.022107,-0.070676,-0.062252
Candidate Native location,-0.137005,-0.114752,0.153663,0.200540,-0.143367,0.025922,-0.191094,0.038561,0.200540,0.225791,...,1.000000,-0.057646,-0.027049,0.008910,-0.060776,-0.059076,0.016755,-0.000673,-0.102416,-0.029513
necessary_permission,-0.050842,-0.016763,-0.245566,0.030127,0.180155,-0.194189,0.097609,0.052591,0.030127,0.037491,...,-0.057646,1.000000,0.642061,0.469906,0.544869,0.643045,0.568186,0.638907,0.754376,0.005977
unscheduled_meetings,0.005164,0.022042,-0.248618,0.030781,0.112453,-0.089955,0.026018,0.017270,0.030781,-0.002150,...,-0.027049,0.642061,1.000000,0.656585,0.614333,0.681461,0.646619,0.594070,0.539248,0.030519
followup_3hours_call,0.035401,0.054909,-0.221951,-0.053203,0.043548,-0.042934,-0.006326,0.009650,-0.053203,-0.060378,...,0.008910,0.469906,0.656585,1.000000,0.609015,0.646915,0.574166,0.506906,0.521016,0.053176
alternative_number,-0.000003,0.032102,-0.188826,-0.030076,0.093617,-0.117416,0.020967,0.100680,-0.030076,-0.008733,...,-0.060776,0.544869,0.614333,0.609015,1.000000,0.589197,0.540135,0.512327,0.669627,0.006059
resume_printout_JD,-0.023218,0.010160,-0.199138,-0.025195,0.097453,-0.078144,0.034290,0.046514,-0.025195,-0.031704,...,-0.059076,0.643045,0.681461,0.646915,0.589197,1.000000,0.574762,0.592125,0.631325,-0.005588
venue_details,-0.001915,0.019023,-0.165873,-0.013943,0.091951,-0.087038,0.003117,0.027956,-0.013943,0.002197,...,0.016755,0.568186,0.646619,0.574166,0.540135,0.574762,1.000000,0.669704,0.564646,0.052506
shared_call_letter,-0.030328,0.027718,-0.200461,-0.024713,0.096457,-0.130858,0.051881,0.079231,-0.024713,-0.043975,...,-0.000673,0.638907,0.594070,0.506906,0.512327,0.592125,0.669704,1.000000,0.691776,0.004831
Expected Attendance,-0.036741,0.017899,-0.248239,-0.054433,0.186404,-0.202855,0.116276,0.043894,-0.054433,-0.051408,...,-0.102416,0.754376,0.539248,0.521016,0.669627,0.631325,0.564646,0.691776,1.000000,0.009643
Marital Status,0.091714,-0.006316,-0.160895,-0.022316,0.068641,-0.068943,0.050913,0.216333,-0.022316,-0.051906,...,-0.029513,0.005977,0.030519,0.053176,0.006059,-0.005588,0.052506,0.004831,0.009643,1.000000

In [45]:
from sklearn.linear_model import LogisticRegression
import numpy as np
#Y_train=interviews1['Observed Attendance']
#del interviews1['Observed Attendance']
#X_train = interviews1
#interviews1.head()
from sklearn.model_selection import train_test_split
interviews.reshape((984,659))
X_train, X_test, y_train, y_test = train_test_split(X_train, Y_train, test_size=0.33, random_state=42)

lm = linear_model.LinearRegression()
model = lm.fit(X_train, y_train)
predictions = lm.predict(y_train)
print(predictions[:5])

plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title('Actual vs Predicted')
plt.legend()
plt.xticks([0,0.5,1.0,1.5,2.0])
plt.yticks([0,0.5,1.0,1.5,2.0,2.5])
plt.scatter(y_test, predictions)
plt.show()
print ("Score:", model.score(X_test, y_test))

#log=LogisticRegression()
#log.fit(X_train,y_train)
#score = log.score(X_test, y_test)
#print(score)

AttributeError: 'DataFrame' object has no attribute 'reshape'